<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class BackupController extends Controller
{
    /**
     * Create database backup
     */
    public function createBackup(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'string|max:255',
            'description' => 'string|max:500',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => 'Validation Error',
                'errors' => $validator->errors()
            ], 422);
        }

        try {
            $timestamp = now()->format('Y-m-d_H-i-s');
            $backupName = $request->name ?? "backup_{$timestamp}";
            $filename = "backup_{$timestamp}.sql";
            
            // Get database configuration
            $database = config('database.connections.mysql.database');
            $username = config('database.connections.mysql.username');
            $password = config('database.connections.mysql.password');
            $host = config('database.connections.mysql.host');
            $port = config('database.connections.mysql.port');

            // Create backups directory if it doesn't exist
            $backupPath = storage_path('app/backups');
            if (!file_exists($backupPath)) {
                mkdir($backupPath, 0755, true);
            }

            $fullPath = $backupPath . '/' . $filename;

            // Try different mysqldump paths
            $mysqldumpPaths = [
                'mysqldump', // System PATH
                'C:\\xampp\\mysql\\bin\\mysqldump.exe', // XAMPP Windows
                '/usr/bin/mysqldump', // Linux
                '/usr/local/bin/mysqldump', // macOS
            ];

            $mysqldumpPath = null;
            foreach ($mysqldumpPaths as $path) {
                if ($this->commandExists($path)) {
                    $mysqldumpPath = $path;
                    break;
                }
            }

            if (!$mysqldumpPath) {
                // Fallback: Create a simple SQL export using PHP
                return $this->createPhpBackup($fullPath, $backupName, $request->description);
            }

            // Create mysqldump command
            $command = sprintf(
                '"%s" --user=%s --password=%s --host=%s --port=%s --single-transaction --routines --triggers %s > "%s" 2>&1',
                $mysqldumpPath,
                $username,
                $password,
                $host,
                $port,
                $database,
                $fullPath
            );

            // Execute backup command
            $output = [];
            $returnCode = 0;
            exec($command, $output, $returnCode);

            if ($returnCode !== 0 || !file_exists($fullPath) || filesize($fullPath) < 100) {
                // If mysqldump fails, try PHP backup
                return $this->createPhpBackup($fullPath, $backupName, $request->description);
            }

            // Get file size
            $fileSize = filesize($fullPath);

            // Store backup info
            $backupInfo = [
                'name' => $backupName,
                'filename' => $filename,
                'description' => $request->description ?? '',
                'size' => $fileSize,
                'created_at' => now()->toISOString(),
                'created_by' => auth()->id(),
                'method' => 'mysqldump'
            ];

            return response()->json([
                'success' => true,
                'data' => $backupInfo,
                'message' => 'Backup created successfully'
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Backup failed',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Create backup using PHP (fallback method)
     */
    private function createPhpBackup($fullPath, $backupName, $description)
    {
        try {
            $database = config('database.connections.mysql.database');
            
            // Get all tables
            $tables = DB::select('SHOW TABLES');
            $tableKey = 'Tables_in_' . $database;
            
            $sql = "-- Database Backup Created: " . now() . "\n";
            $sql .= "-- Database: {$database}\n";
            $sql .= "-- Generated by: PHP Backup Method\n\n";
            
            $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
            
            foreach ($tables as $table) {
                $tableName = $table->$tableKey;
                
                // Get table structure
                $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`");
                $sql .= "-- Table structure for `{$tableName}`\n";
                $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n";
                $sql .= $createTable[0]->{'Create Table'} . ";\n\n";
                
                // Get table data
                $rows = DB::table($tableName)->get();
                if ($rows->count() > 0) {
                    $sql .= "-- Data for table `{$tableName}`\n";
                    $sql .= "INSERT INTO `{$tableName}` VALUES\n";
                    
                    $values = [];
                    foreach ($rows as $row) {
                        $rowData = [];
                        foreach ($row as $value) {
                            if (is_null($value)) {
                                $rowData[] = 'NULL';
                            } else {
                                $rowData[] = "'" . addslashes($value) . "'";
                            }
                        }
                        $values[] = '(' . implode(',', $rowData) . ')';
                    }
                    
                    $sql .= implode(",\n", $values) . ";\n\n";
                }
            }
            
            $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
            
            // Write to file
            file_put_contents($fullPath, $sql);
            
            $backupInfo = [
                'name' => $backupName,
                'filename' => basename($fullPath),
                'description' => $description ?? '',
                'size' => filesize($fullPath),
                'created_at' => now()->toISOString(),
                'created_by' => auth()->id(),
                'method' => 'php'
            ];

            return response()->json([
                'success' => true,
                'data' => $backupInfo,
                'message' => 'Backup created successfully using PHP method'
            ]);
            
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'PHP backup failed',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Check if command exists
     */
    private function commandExists($command)
    {
        $whereIsCommand = (PHP_OS == 'WINNT') ? 'where' : 'which';
        $process = proc_open(
            "$whereIsCommand $command",
            [
                0 => ['pipe', 'r'], // stdin
                1 => ['pipe', 'w'], // stdout
                2 => ['pipe', 'w'], // stderr
            ],
            $pipes
        );
        
        if ($process !== false) {
            $stdout = stream_get_contents($pipes[1]);
            $stderr = stream_get_contents($pipes[2]);
            fclose($pipes[1]);
            fclose($pipes[2]);
            $returnCode = proc_close($process);
            return $returnCode === 0;
        }
        
        return false;
    }

    /**
     * List all backups
     */
    public function listBackups()
    {
        try {
            $backupPath = storage_path('app/backups');
            $backups = [];

            if (is_dir($backupPath)) {
                $files = scandir($backupPath);
                
                foreach ($files as $file) {
                    if ($file !== '.' && $file !== '..' && pathinfo($file, PATHINFO_EXTENSION) === 'sql') {
                        $fullPath = $backupPath . '/' . $file;
                        $backups[] = [
                            'filename' => $file,
                            'name' => pathinfo($file, PATHINFO_FILENAME),
                            'size' => filesize($fullPath),
                            'created_at' => date('Y-m-d H:i:s', filemtime($fullPath)),
                            'path' => $fullPath,
                        ];
                    }
                }

                // Sort by creation time (newest first)
                usort($backups, function($a, $b) {
                    return strtotime($b['created_at']) - strtotime($a['created_at']);
                });
            }

            return response()->json([
                'success' => true,
                'data' => $backups,
                'message' => 'Backups retrieved successfully'
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to list backups',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Download backup file
     */
    public function downloadBackup($filename)
    {
        try {
            $backupPath = storage_path('app/backups/' . $filename);

            if (!file_exists($backupPath)) {
                return response()->json([
                    'success' => false,
                    'message' => 'Backup file not found'
                ], 404);
            }

            return response()->download($backupPath);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Download failed',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Delete backup file
     */
    public function deleteBackup($filename)
    {
        try {
            $backupPath = storage_path('app/backups/' . $filename);

            if (!file_exists($backupPath)) {
                return response()->json([
                    'success' => false,
                    'message' => 'Backup file not found'
                ], 404);
            }

            unlink($backupPath);

            return response()->json([
                'success' => true,
                'message' => 'Backup deleted successfully'
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Delete failed',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Get system usage statistics
     */
    public function getSystemUsage()
    {
        try {
            $stats = [
                'database' => [
                    'total_tables' => DB::select("SELECT COUNT(*) as count FROM information_schema.tables WHERE table_schema = ?", [config('database.connections.mysql.database')])[0]->count,
                    'total_users' => DB::table('users')->count(),
                ],
                'storage' => [
                    'backup_count' => count(glob(storage_path('app/backups/*.sql'))),
                    'backup_size' => $this->getDirectorySize(storage_path('app/backups')),
                ],
                'activity' => [
                    'users_today' => DB::table('users')->whereDate('created_at', today())->count(),
                    'users_this_week' => DB::table('users')->whereBetween('created_at', [now()->startOfWeek(), now()->endOfWeek()])->count(),
                    'users_this_month' => DB::table('users')->whereMonth('created_at', now()->month)->count(),
                ]
            ];

            return response()->json([
                'success' => true,
                'data' => $stats,
                'message' => 'System usage statistics retrieved successfully'
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to get system usage',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * Helper function to get directory size
     */
    private function getDirectorySize($directory)
    {
        $size = 0;
        if (is_dir($directory)) {
            foreach (glob($directory . '/*') as $file) {
                if (is_file($file)) {
                    $size += filesize($file);
                }
            }
        }
        return $size;
    }
}